version: '3'

services:
  dynamodb:
    image: amazon/dynamodb-local:latest
    container_name: dynamodb-local-latest
    command: -jar DynamoDBLocal.jar -sharedDb -inMemory -port 8000
    ports:
      - '8000:8000'
    working_dir: /home/dynamodblocal