version: '2.1'

services:
  dynamodb:
    image: amazon/dynamodb-local:latest
    command: -jar DynamoDBLocal.jar -sharedDb -inMemory -port 8001
    ports:
      - '8000:8000'
    working_dir: /home/dynamodblocal