---
name: 'Twitter Summariser CI'

on: 
  pull_request:
    branches:
      - develop

jobs:
  milestone-check:
    name: Checks if milestone is used
    runs-on: ubuntu-latest
    steps:       
      - name: Has milestone check
        if: github.event.pull_request.milestone == null
        run: |
          echo "you don't have a milestone"
          exit 1

  label-check:
    name: Checks if labels are used
    runs-on: ubuntu-latest
    needs: milestone-check

    steps: 
      - name: Checking out to the develop branch
        uses: actions/checkout@v2

      - name: Has atleast one priority label
        uses: mheap/github-action-required-labels@v1
        with:
          mode: minimum
          count: 1
          labels: 'priority:high, priority:low, priority:medium'

      - name: Has atleast one type label
        uses: mheap/github-action-required-labels@v1
        with:
          mode: minimum
          count: 1
          labels: 'type:bug, type:change, type:documentation, type:enhance, type:fix, type:meeting, type:test'

      - name: Has atleast one status label
        uses: mheap/github-action-required-labels@v1
        with:
          mode: minimum
          count: 1
          labels: 'status:needs-tests, status:not-ready, status:ready'

      - name: Has atleast one role label
        uses: mheap/github-action-required-labels@v1
        with:
          mode: minimum
          count: 1
          labels: 'role:frontend-engineer, role:business-analyst, role:backend-engineer, role:dev-op, role:team-lead, role:tester, role:designer'
      
      - name: Has atleast one scope label
        uses: mheap/github-action-required-labels@v1
        with:
          mode: minimum
          count: 1
          labels: 'scope:ai, scope:cicd, scope:github-repo, scope:db, scope:frontend,scope:backend'

  Build-and-Deploy-Frontend:
    runs-on: ubuntu-latest
    needs: label-check
    defaults:
      run:
        working-directory: client

    steps:
      - name: Checkout to develop branch
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'

      - name: Install all package dependencies
        run: npm install

      - name: Lint the code and format the files
        run: npm run test-eslint

      - name: Generate coverage report
        run:  npm test -- --coverage --watchAll=false

      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build the project
        run: CI=false npm run build

      - name: Configure AWS tokens
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Deploy the React App to S3 Bucket
        run: aws s3 cp build s3://twitter-summariser-bucket/ --recursive
          
  Build-and-Deploy-Backend:
      runs-on: ubuntu-latest
      needs: label-check
      defaults:
        run:
          working-directory: infrastructure

      steps:
      - name: Checkout to develop branch
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'

      - name: Install all package dependencies
        run: npm install

      - name: Configure AWS tokens
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Install CDK
        run: npm install -g aws-cdk

      - name: Build the CDK
        run: npm run build

      - name: Synthesize the CDK
        run: cdk synth

      - name: Deploy the CDK to AWS
        run: cdk deploy --require-approval never