name: Serverless Deploy

on:
  pull_request:
    branches:
      - develop
    types:
      - closed

jobs:
  Serverless-Deploy:
    if: ${{ github.event.pull_request.merged }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - name: Checkout to develop branch
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install package dependencies for backend
        run: yarn

      - name: Install package dependencies for the React App and build it
        run: |
          cd client
          yarn
          CI=false yarn run build

      - name: Serverless deploy
        uses: serverless/github-action@v3
        with:
          args: deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Invalidating Cloudfrount Cache
        run: |
          npm i -g aws-cli
          npm i -g aws-sdk
          npm i @aws-cdk/aws-cloudfront
          aws cloudfront create-invalidation --distribution-id E2MJZ6KHWRD9W0 --paths "/*" 
