name: Serverless Deploy

on:
  pull_request:
    branches:
      - develop
    types:
      - closed

jobs:
  Serverless-Deploy:
    if: ${{ github.event.pull_request.merged }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to develop/master branch
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: Download the Twitter Summariser artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: build.yml
          name: client-artifact
          path: client/build
    
      - name: Install package dependencies for backend
        run: yarn

      - name: Serverless Deploy
        uses: serverless/github-action@v3
        with:
          args: deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Invalidating Cloudfrount Cache
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-1
        run: |
          npm i -g aws-cli
          npm i -g aws-sdk
          npm i @aws-cdk/aws-cloudfront
          aws cloudfront create-invalidation --distribution-id E1SMKKY29H5MJB --paths "/*" 

      - name: Run Prettier and fomat the code
        uses: creyD/prettier_action@v4.2
        with:
          prettier_options: --write . --config .prettierrc
          commit_message: "ðŸŽ¨(CICD): All code has been formatted!"
